/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.ptcd.nhatrosystem.ui;

import com.fpt.ptcd.nhatrosystem.dao.MucGiaDAO;
import com.fpt.ptcd.nhatrosystem.entity.MucGia;
import com.fpt.ptcd.nhatrosystem.utils.MsgBox;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 24010
 */
public class MucGiaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form TyGiaJDialog
     */
    public MucGiaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        spnTienDienBac1 = new javax.swing.JSpinner();
        spnTienNuocBac1 = new javax.swing.JSpinner();
        spnTienRac = new javax.swing.JSpinner();
        spnTienWifi = new javax.swing.JSpinner();
        spnTienDienBac2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblkWhBac1 = new javax.swing.JLabel();
        lblkWhBac2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spnTienDienBac3 = new javax.swing.JSpinner();
        lblkWhBac3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spnTienDienBac4 = new javax.swing.JSpinner();
        lblkWhBac4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spnTienDienBac5 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        lblkWhBac5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spnTienDienBac6 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        lblkWhBac6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTienNuocBac1 = new javax.swing.JLabel();
        spnTienNuocBac2 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblTienNuocBac2 = new javax.swing.JLabel();
        lblTienNuocBac3 = new javax.swing.JLabel();
        spnTienNuocBac3 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblTienNuocBac4 = new javax.swing.JLabel();
        spnTienNuocBac4 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblQL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQL.setForeground(new java.awt.Color(0, 0, 255));
        lblQL.setText("QUẢN LÝ MỨC GIÁ");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tiền Điện/kWh");

        jLabel3.setText("Tiền Nước/m3");

        jLabel4.setText("Tiền Wifi/phòng");

        jLabel5.setText("Tiền Rác/phòng");

        btnLuu.setText("Lưu");
        btnLuu.setHideActionText(true);
        btnLuu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setText("Bậc 1");

        jLabel6.setText("Bậc 2");

        lblkWhBac1.setText("0kWh-50kWh");

        lblkWhBac2.setText("51kWh-100kWh");

        jLabel9.setText("Bậc 3");

        lblkWhBac3.setText("101kWh-200kWh");

        jLabel7.setText("VNĐ /");

        jLabel8.setText("VNĐ /");

        jLabel10.setText("VNĐ /");

        jLabel11.setText("VNĐ /");

        jLabel12.setText("Bậc 4");

        lblkWhBac4.setText("201kWh-300kWh");

        jLabel13.setText("VNĐ /");

        jLabel14.setText("Bậc 5");

        lblkWhBac5.setText("301kWh-400kWh");

        jLabel15.setText("VNĐ /");

        jLabel16.setText("Bậc 6");

        lblkWhBac6.setText("Trên 400kWh");

        jLabel17.setText("Bậc 1");

        jLabel18.setText("VNĐ /");

        lblTienNuocBac1.setText("0m3-10m3");

        jLabel19.setText("Bậc 2");

        jLabel20.setText("VNĐ /");

        lblTienNuocBac2.setText("11m3-20m3");

        lblTienNuocBac3.setText("21m3-30m3");

        jLabel21.setText("Bậc 3");

        jLabel22.setText("VNĐ /");

        lblTienNuocBac4.setText("Trên 30m3");

        jLabel23.setText("Bậc 4");

        jLabel24.setText("VNĐ /");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(spnTienNuocBac1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(spnTienNuocBac2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(6, 6, 6)
                                .addComponent(lblTienNuocBac2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(6, 6, 6)
                                .addComponent(lblTienNuocBac1)
                                .addContainerGap(157, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(spnTienNuocBac3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(6, 6, 6)
                                .addComponent(lblTienNuocBac3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(spnTienNuocBac4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addGap(6, 6, 6)
                                .addComponent(lblTienNuocBac4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(spnTienRac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addComponent(spnTienWifi)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(spnTienDienBac1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel9))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(spnTienDienBac3)
                                                        .addComponent(spnTienDienBac2))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel13)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(spnTienDienBac5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(spnTienDienBac4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblkWhBac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblkWhBac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblkWhBac3)
                                                .addComponent(lblkWhBac4)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblkWhBac5)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(spnTienDienBac6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(169, 169, 169)
                                        .addComponent(jLabel15)))
                                .addGap(18, 18, 18)
                                .addComponent(lblkWhBac6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addGap(9, 9, 9))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnTienDienBac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkWhBac1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTienDienBac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblkWhBac2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spnTienDienBac3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkWhBac3)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spnTienDienBac4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkWhBac4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(spnTienDienBac5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkWhBac5)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(spnTienDienBac6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkWhBac6)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(spnTienNuocBac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(lblTienNuocBac1))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(spnTienNuocBac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(lblTienNuocBac2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(spnTienNuocBac3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(lblTienNuocBac3))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(spnTienNuocBac4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(lblTienNuocBac4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spnTienWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTienRac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQL)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.thoat();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MucGiaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MucGiaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MucGiaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MucGiaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MucGiaJDialog dialog = new MucGiaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQL;
    private javax.swing.JLabel lblTienNuocBac1;
    private javax.swing.JLabel lblTienNuocBac2;
    private javax.swing.JLabel lblTienNuocBac3;
    private javax.swing.JLabel lblTienNuocBac4;
    private javax.swing.JLabel lblkWhBac1;
    private javax.swing.JLabel lblkWhBac2;
    private javax.swing.JLabel lblkWhBac3;
    private javax.swing.JLabel lblkWhBac4;
    private javax.swing.JLabel lblkWhBac5;
    private javax.swing.JLabel lblkWhBac6;
    private javax.swing.JSpinner spnTienDienBac1;
    private javax.swing.JSpinner spnTienDienBac2;
    private javax.swing.JSpinner spnTienDienBac3;
    private javax.swing.JSpinner spnTienDienBac4;
    private javax.swing.JSpinner spnTienDienBac5;
    private javax.swing.JSpinner spnTienDienBac6;
    private javax.swing.JSpinner spnTienNuocBac1;
    private javax.swing.JSpinner spnTienNuocBac2;
    private javax.swing.JSpinner spnTienNuocBac3;
    private javax.swing.JSpinner spnTienNuocBac4;
    private javax.swing.JSpinner spnTienRac;
    private javax.swing.JSpinner spnTienWifi;
    // End of variables declaration//GEN-END:variables
    MucGiaDAO dao = new MucGiaDAO();

    void init() {
        setLocationRelativeTo(null); // đưa cửa sổ ra giữa màn hình
        this.fillForm(); // đổ dữ liệu nhân viên vào bảng

    }

    void fillForm() {
        List<MucGia> list = dao.selectAll();
        if (!list.isEmpty()) {
            MucGia mucGia = list.get(0);

            spnTienDienBac1.setValue(mucGia.getTienDienBac1());
            spnTienDienBac2.setValue(mucGia.getTienDienBac2());
            spnTienDienBac3.setValue(mucGia.getTienDienBac3());
            spnTienDienBac4.setValue(mucGia.getTienDienBac4());
            spnTienDienBac5.setValue(mucGia.getTienDienBac5());
            spnTienDienBac6.setValue(mucGia.getTienDienBac6());
            spnTienNuocBac1.setValue(mucGia.getTienNuocBac1());
            spnTienNuocBac2.setValue(mucGia.getTienNuocBac2());
            spnTienNuocBac3.setValue(mucGia.getTienNuocBac3());
            spnTienNuocBac4.setValue(mucGia.getTienNuocBac4());
            spnTienWifi.setValue(mucGia.getTienWifi());
            spnTienRac.setValue(mucGia.getTienRac());
        }
    }

    void update() {
        MucGia mucGia = this.getForm();
        boolean kqkt = kiemTraDinhDang(mucGia);
        if (kqkt) {
            try {
                dao.update(mucGia);

                MsgBox.alert(this, "Cập nhật mức giá thành công!");
                fillForm();
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại loi: " + e.getMessage());
            }
        }
    }

    MucGia getForm() {
        MucGia mucGia = new MucGia();
        mucGia.setTienDienBac1(((Number) spnTienDienBac1.getValue()).doubleValue());
        mucGia.setTienDienBac2(((Number) spnTienDienBac2.getValue()).doubleValue());
        mucGia.setTienDienBac3(((Number) spnTienDienBac3.getValue()).doubleValue());
        mucGia.setTienDienBac4(((Number) spnTienDienBac4.getValue()).doubleValue());
        mucGia.setTienDienBac5(((Number) spnTienDienBac5.getValue()).doubleValue());
        mucGia.setTienDienBac6(((Number) spnTienDienBac6.getValue()).doubleValue());

        mucGia.setTienNuocBac1(((Number) spnTienNuocBac1.getValue()).doubleValue());
        mucGia.setTienNuocBac2(((Number) spnTienNuocBac2.getValue()).doubleValue());
        mucGia.setTienNuocBac3(((Number) spnTienNuocBac3.getValue()).doubleValue());
        mucGia.setTienNuocBac4(((Number) spnTienNuocBac4.getValue()).doubleValue());

        mucGia.setTienWifi(((Number) spnTienWifi.getValue()).doubleValue());
        mucGia.setTienRac(((Number) spnTienRac.getValue()).doubleValue());

        return mucGia;
    }

    boolean kiemTraDinhDang(MucGia mucGia) {
        try {
            double[] dien = {mucGia.getTienDienBac1(), mucGia.getTienDienBac2(), mucGia.getTienDienBac3(),
                mucGia.getTienDienBac4(), mucGia.getTienDienBac5(), mucGia.getTienDienBac6()};

            double[] nuoc = {mucGia.getTienNuocBac1(), mucGia.getTienNuocBac2(), mucGia.getTienNuocBac3(), mucGia.getTienNuocBac4()};

            for (double gia : dien) {
                if (gia < 0) {
                    MsgBox.alert(this, "Giá điện không được âm");
                    return false;
                }
            }

            for (double gia : nuoc) {
                if (gia < 0) {
                    MsgBox.alert(this, "Giá nước không được âm");
                    return false;
                }
            }

            for (int i = 0; i < dien.length - 1; i++) {
                if (dien[i] > dien[i + 1]) {
                    MsgBox.alert(this, "Giá điện phải tăng dần theo bậc");
                    return false;
                }
            }

            
            for (int i = 0; i < nuoc.length - 1; i++) {
                if (nuoc[i] > nuoc[i + 1]) {
                    MsgBox.alert(this, "Giá nước phải tăng dần theo bậc");
                    return false;
                }
            }

            return true;
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Vui lòng nhập số hợp lệ.");
            return false;
        }
    }

    void thoat() {
        setVisible(false);
    }

    //Chưa thử
    public double tinhTienDien(double soKWh, double bac1, double bac2, double bac3) {
        double tienDien = 0;

        if (soKWh <= 50) {
            // nếu dùng dưới 50 kWh tính theo giá bậc 1
            tienDien = soKWh * bac1;
        } else if (soKWh <= 150) {
            // nếu dùng từ 51-150 kWh
            tienDien = (50 * bac1) + ((soKWh - 50) * bac2);
        } else {
            // nếu dùng trên 150 kWh
            tienDien = (50 * bac1) + (100 * bac2) + ((soKWh - 150) * bac3);
        }

        return tienDien;
    }

    public double tinhTienNuoc(double soM3, double giaNuoc) {
        if (soM3 < 0) {
            MsgBox.alert(this, "Số m³ nước không thể âm!");
        }
        return soM3 * giaNuoc;
    }

    public double tinhTienWifi(double giaWifi) {
        if (giaWifi < 0) {
            throw new IllegalArgumentException("Tiền WiFi không thể âm!");
        }
        return giaWifi;
    }

    public double tinhTienRac(double giaRac) {
        if (giaRac < 0) {
            MsgBox.alert(this, "Tiền rác không thể âm!");
        }
        return giaRac;
    }

}
